<?php

/**
 * @file
 * YUSA OpenY YMCA360 integration installation routines.
 */

/**
 * Implements hook_install().
 */
function yusaopeny_ymca360_livestreams_install() {
  $config = \Drupal::configFactory()->getEditable('ymca_sync.settings');
  $active_syncers = $config->get('active_syncers');
  $active_syncers[] = 'yusaopeny_ymca360_livestreams.syncer';
  $config->set('active_syncers', $active_syncers);
  $config->save();
}

/**
 * Implements hook_install().
 */
function yusaopeny_ymca360_livestreams_uninstall() {
  $config = \Drupal::configFactory()->getEditable('ymca_sync.settings');
  $active_syncers = $config->get('active_syncers');
  $active_syncers = array_filter($active_syncers, function ($value) {
    return $value !== 'yusaopeny_ymca360_livestreams.syncer';
  });
  $config->set('active_syncers', $active_syncers);
  $config->save();
}
